services:
    db:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sistema_turnos
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d sistema_turnos']
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build: .
        restart: always
        ports:
            - '3000:3000'
        depends_on:
            db:
                condition: service_healthy
        environment:
            PORT: 3000
            DB_HOST: db
            DB_PORT: 5432
            DB_NAME: sistema_turnos
            DB_USER: postgres
            DB_PASSWORD: postgres

volumes:
    pg_data:
